### ISSUE TITLE
L1 vs L2

### ISSUE THREAD

**Issue by KatsarosEf** [zzh-tech/ESTRNN#12]
Hi, congratulations on your work and thanks for sharing your code and dataset! 

I have a question, you mention in the paper "For the synthentic dataset GOPRO and REDS, the loss function is uniformly defined as L2 loss; while for the proposed dataset BSD, we use L1 for each model ..." 

Is there any motivation behind that choice, or was it purely due to performance gains? Moreover, would there be any case you could share the difference in PSNR between L1 and L2?

Many thanks!

**Comment by zzh-tech** [comment]
Hi, the reason we use L1 for BSD is that misalignment exists in the blurry/sharp pairs of the old BSD dataset (the one we used in the ECCV2020 paper). L1 is less sensitive to position than L2 and therefore leads to better PSNR performance.
In the new version of the BSD dataset, we simply use the Charbonnier loss. For other losses, we have not explored much. You are welcome to try other losses, such as perceptual loss, GAN loss and so on.

**Comment by KatsarosEf** [comment]
Thanks for your swift reply. I am actually performing experiments for a work of mine on your database and I'd like to ask the following two questions; Is this misalignment due to the beam splitter? How is the second dataset version improved (for instance, with camera calibration or better spatial warping) ?

**Comment by zzh-tech** [comment]
> Is this misalignment due to the beam splitter?

When using a beam splitter, the two cameras should be mechanically aligned assisted with collimated laser beams.
However, the eccv version does not do the strict alignment as above and firm fixing.

> How is the second dataset version improved (for instance, with camera calibration or better spatial warping) ?

The second dataset version solves the problem mentioned in the first question.
In addition, we adopted a center-aligned scheme instead of a start-aligned scheme in the second version for better alignment. (Please see the difference between the Fig. 5(b) in the eccv paper and the one in the README.md)

**Comment by KatsarosEf** [comment]
Thanks!
