### ISSUE TITLE
Some questions about --trainer_mode dp and DataLoader

### ISSUE THREAD

**Issue by pp00704831** [zzh-tech/ESTRNN#5]
Hello,

First,  
Do you experiment on dp version before? 
I find that dp runs faster than ddp with the same batch_size and GPU numbers, but why do you use ddp to train?

Second,
In the gopro_ds_lmdb.py, you used DeblurDataset() to generate video deblurring datasets.
You used random.randint to chose seq_idx and frame_idx, but will it cause some to choose repeatedly?
Whether it will cause some images in GoPro datasets never be chosen at all?

Looking forward to your reply! Thank you very much!

 
![image](https://user-images.githubusercontent.com/57279608/100842709-37365f80-34b4-11eb-9dd7-5207f6daedbc.png)

**Comment by zzh-tech** [comment]
*\>\> I find that dp runs faster than ddp with the same batch_size and GPU numbers, but why do you use ddp to train?*

The actual batch size of ddp mode is "num_gpus X batch_size".
There is an issue needed to be fixed for ddp mode in this version, that the num_workers of DataLoader cannot be set larger than 0.
This issue has been fixed in the new version.
I will update the code and BSD dataset before the end of this month.

*\>\> You used random.randint to chose seq_idx and frame_idx, but will it cause some to choose repeatedly? Whether it will cause some images in GoPro datasets never be chosen at all?*

It will.
I don't think it will hinder training, since the model will be trained for hundreds of epochs with different possible sequences.
But you can try traversing the entire dataset to see if it's better.

**Comment by pp00704831** [comment]
Hello,
May I ask you about your Cuda version?
Cause I use your code as the backbone for my school homework, I change with a smaller model.
But this problem will occur: 'cuDNN error: CUDNN_STATUS_INTERNAL_ERROR' when I use multi GPU in the dp mode.
I googled it and I found that it might cause by incompatible with the Cuda version. 
Thank you very much!

**Comment by zzh-tech** [comment]
I have successfully used CUDA10.1, 10.2 and 11 before.

**Comment by pp00704831** [comment]
Okay, I got it, Thank you very much!
